//
//  main.swift
//  LC-Swift
//
//  Created by Songyu on 2019/4/15.
//  Copyright © 2019 Songyu. All rights reserved.
//

import Foundation

// MARK: - Array
//TwoSumSoluton().test()
//medianOfTwoSortedArraysSolution().test()
//ContainerWithMostWaterSolution().test()
//ThreeSumSolution().test()
//ThreeSumClosestSolution().test()
//FourSumSolution().test()
//RemoveDuplicatesFromSortedArray().test()
//RemoveElementSolution().test()
//NextPermutationSolution().test()
//SearchInRotatedSortedArraySolution().test()
//SearchInsertPositionSolution().test()
//MaximumSubarraySolution().test()
//PlusOneSolution().test()
//MergeSortedArraySolution().test()
//PascalsTriangleSolution().test()
//PascalsTriangleIISolution().test()
//BestTimeToBuyAndSellStockSolution().test()
//BestTimeToBuyAndSellStockIISolution().test()
//SingleNumberSolution().test()
//TwoSumIIInputArrayIsSortedSolution().test()
//MajorityElementSolution().test()
//RotateArraySolution().test()
//ContainsDuplicateSolution().test()
//ContainsDuplicateIISolution().test()
//MissingNumberSolution().test()
//MoveZeroesSolution().test()
//ThirdMaximumNumberSolution().test()
//FindAllNumbersDisappearedInAnArraySolution().test()
//MaxConsecutiveOnesSolution().test()
//FibonacciNumberSolution().test()
//KdiffPairsInAnArraySolution().test()
//ArrayPartitionISolution().test()
//ReshapeTheMatrixSolution().test()
//ShortestUnsortedContinuousSubarraySolution().test()
//MaximumProductOfThreeNumbersSolution().test()
//MaximumAverageSubarrayISolution().test()
//ImageSmootherSolution().test()
//LongestContinuousIncreasingSubsequenceSolution().test()
//DegreeOfAnArraySolution().test()
//OnebitAndTwobitCharactersSolution().test()
//FindPivotIndexSolution().test()
//MinCostClimbingStairsSolution().test()
//LargestNumberAtLeastTwiceOfOthersSolution().test()
//ToeplitzMatrixSolution().test()
//PositionsOfLargeGroupsSolution().test()
//FlippingAnImageSolution().test()
//MaximizeDistanceToClosestPersonSolution().test()
//TransposeMatrixSolution().test()
//FairCandySwapSolution().test()
//MonotonicArraySolution().test()
//SortArrayByParitySolution().test()
//SortArrayByParityIISolution().test()
//ValidMountainArraySolution().test()
//SquaresOfASortedArraySolution().test()
//SumOfEvenNumbersAfterQueriesSolution().test()
//AddToArrayFormOfIntegerSolution().test()
//AvailableCapturesForRookSolution().test()
//FindCommonCharactersSolution().test()
//PairsOfSongsWithTotalDurationsDivisibleBy60Solution().test()
//PartitionArrayIntoThreePartsWithEqualSumSolution().test()
//BinaryPrefixDivisibleBy5Solution().test()

// MARK: - Linked List
//AddTwoNumbersSolution().test()
//ReverseLinkedListSolution().test()
//_237_DeleteNodeInAlinkedList().test()
MiddleOfTheLinkedListSolution().test()
